// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package audio

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio(in *jlexer.Lexer, out *VoiceConsentListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Object = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]VoiceConsent, 0, 0)
					} else {
						out.Data = []VoiceConsent{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 VoiceConsent
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "first_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstID = string(in.String())
			}
		case "last_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = string(in.String())
			}
		case "has_more":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasMore = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio(out *jwriter.Writer, in VoiceConsentListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix[1:])
		out.String(string(in.Object))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.FirstID != "" {
		const prefix string = ",\"first_id\":"
		out.RawString(prefix)
		out.String(string(in.FirstID))
	}
	if in.LastID != "" {
		const prefix string = ",\"last_id\":"
		out.RawString(prefix)
		out.String(string(in.LastID))
	}
	{
		const prefix string = ",\"has_more\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasMore))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VoiceConsentListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VoiceConsentListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VoiceConsentListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VoiceConsentListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio1(in *jlexer.Lexer, out *VoiceConsent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Object = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio1(out *jwriter.Writer, in VoiceConsent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix[1:])
		out.String(string(in.Object))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VoiceConsent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VoiceConsent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VoiceConsent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VoiceConsent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio1(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio2(in *jlexer.Lexer, out *Voice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Object = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio2(out *jwriter.Writer, in Voice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix[1:])
		out.String(string(in.Object))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Voice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Voice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Voice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Voice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio2(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio3(in *jlexer.Lexer, out *UpdateVoiceConsentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio3(out *jwriter.Writer, in UpdateVoiceConsentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateVoiceConsentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateVoiceConsentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateVoiceConsentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateVoiceConsentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio3(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio4(in *jlexer.Lexer, out *Translation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio4(out *jwriter.Writer, in Translation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Translation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Translation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Translation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Translation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio4(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio5(in *jlexer.Lexer, out *Transcription) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio5(out *jwriter.Writer, in Transcription) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	if in.Language != "" {
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	if in.Duration != 0 {
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.Float64(float64(in.Duration))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transcription) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transcription) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transcription) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transcription) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio5(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio6(in *jlexer.Lexer, out *SpeechRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Input = string(in.String())
			}
		case "voice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Voice = string(in.String())
			}
		case "response_format":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Format = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio6(out *jwriter.Writer, in SpeechRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		out.String(string(in.Input))
	}
	{
		const prefix string = ",\"voice\":"
		out.RawString(prefix)
		out.String(string(in.Voice))
	}
	if in.Format != "" {
		const prefix string = ",\"response_format\":"
		out.RawString(prefix)
		out.String(string(in.Format))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SpeechRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SpeechRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SpeechRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SpeechRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio6(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio7(in *jlexer.Lexer, out *DeleteVoiceConsentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Object = string(in.String())
			}
		case "deleted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Deleted = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio7(out *jwriter.Writer, in DeleteVoiceConsentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix)
		out.String(string(in.Object))
	}
	{
		const prefix string = ",\"deleted\":"
		out.RawString(prefix)
		out.Bool(bool(in.Deleted))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteVoiceConsentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteVoiceConsentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOpenaiAudio7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteVoiceConsentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteVoiceConsentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOpenaiAudio7(l, v)
}
