// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package generate

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "response":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Response = string(in.String())
			}
		case "done":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Done = bool(in.Bool())
			}
		case "total_duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalDuration = int64(in.Int64())
			}
		case "load_duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LoadDuration = int64(in.Int64())
			}
		case "prompt_eval_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptEvalCount = int(in.Int())
			}
		case "eval_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EvalCount = int(in.Int())
			}
		case "done_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DoneReason = string(in.String())
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Thinking = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.Response != "" {
		const prefix string = ",\"response\":"
		out.RawString(prefix)
		out.String(string(in.Response))
	}
	{
		const prefix string = ",\"done\":"
		out.RawString(prefix)
		out.Bool(bool(in.Done))
	}
	if in.TotalDuration != 0 {
		const prefix string = ",\"total_duration\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalDuration))
	}
	if in.LoadDuration != 0 {
		const prefix string = ",\"load_duration\":"
		out.RawString(prefix)
		out.Int64(int64(in.LoadDuration))
	}
	if in.PromptEvalCount != 0 {
		const prefix string = ",\"prompt_eval_count\":"
		out.RawString(prefix)
		out.Int(int(in.PromptEvalCount))
	}
	if in.EvalCount != 0 {
		const prefix string = ",\"eval_count\":"
		out.RawString(prefix)
		out.Int(int(in.EvalCount))
	}
	if in.DoneReason != "" {
		const prefix string = ",\"done_reason\":"
		out.RawString(prefix)
		out.String(string(in.DoneReason))
	}
	if in.Thinking != "" {
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		out.String(string(in.Thinking))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate1(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "prompt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Prompt = string(in.String())
			}
		case "suffix":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Suffix = string(in.String())
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "format":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Format).UnmarshalJSON(data))
				}
			}
		case "options":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Options).UnmarshalJSON(data))
				}
			}
		case "keep_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KeepAlive = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate1(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	if in.Prompt != "" {
		const prefix string = ",\"prompt\":"
		out.RawString(prefix)
		out.String(string(in.Prompt))
	}
	if in.Suffix != "" {
		const prefix string = ",\"suffix\":"
		out.RawString(prefix)
		out.String(string(in.Suffix))
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.Bool(bool(in.Stream))
	}
	if len(in.Format) != 0 {
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.Raw((in.Format).MarshalJSON())
	}
	if len(in.Options) != 0 {
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		out.Raw((in.Options).MarshalJSON())
	}
	if in.KeepAlive != "" {
		const prefix string = ",\"keep_alive\":"
		out.RawString(prefix)
		out.String(string(in.KeepAlive))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaGenerate1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaGenerate1(l, v)
}
