// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package lora

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaLora(in *jlexer.Lexer, out *Adapter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "scale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scale = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaLora(out *jwriter.Writer, in Adapter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"scale\":"
		out.RawString(prefix)
		out.Float64(float64(in.Scale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Adapter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaLora(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Adapter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaLora(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Adapter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaLora(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Adapter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaLora(l, v)
}
