// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package completions

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions(in *jlexer.Lexer, out *TokenProbability) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "logprob":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogProbability = float64(in.Float64())
			}
		case "prob":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Probability = float64(in.Float64())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "bytes":
			if in.IsNull() {
				in.Skip()
				out.Bytes = nil
			} else {
				in.Delim('[')
				if out.Bytes == nil {
					if !in.IsDelim(']') {
						out.Bytes = make([]int, 0, 8)
					} else {
						out.Bytes = []int{}
					}
				} else {
					out.Bytes = (out.Bytes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					out.Bytes = append(out.Bytes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "top_logprobs":
			if in.IsNull() {
				in.Skip()
				out.TopLogProbabilities = nil
			} else {
				in.Delim('[')
				if out.TopLogProbabilities == nil {
					if !in.IsDelim(']') {
						out.TopLogProbabilities = make([]TokenProbability, 0, 0)
					} else {
						out.TopLogProbabilities = []TokenProbability{}
					}
				} else {
					out.TopLogProbabilities = (out.TopLogProbabilities)[:0]
				}
				for !in.IsDelim(']') {
					var v2 TokenProbability
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.TopLogProbabilities = append(out.TopLogProbabilities, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "top_probs":
			if in.IsNull() {
				in.Skip()
				out.TopProbabilities = nil
			} else {
				in.Delim('[')
				if out.TopProbabilities == nil {
					if !in.IsDelim(']') {
						out.TopProbabilities = make([]TokenProbability, 0, 0)
					} else {
						out.TopProbabilities = []TokenProbability{}
					}
				} else {
					out.TopProbabilities = (out.TopProbabilities)[:0]
				}
				for !in.IsDelim(']') {
					var v3 TokenProbability
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.TopProbabilities = append(out.TopProbabilities, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions(out *jwriter.Writer, in TokenProbability) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	if in.LogProbability != 0 {
		const prefix string = ",\"logprob\":"
		out.RawString(prefix)
		out.Float64(float64(in.LogProbability))
	}
	if in.Probability != 0 {
		const prefix string = ",\"prob\":"
		out.RawString(prefix)
		out.Float64(float64(in.Probability))
	}
	if in.Token != "" {
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	if len(in.Bytes) != 0 {
		const prefix string = ",\"bytes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v4, v5 := range in.Bytes {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v5))
			}
			out.RawByte(']')
		}
	}
	if len(in.TopLogProbabilities) != 0 {
		const prefix string = ",\"top_logprobs\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.TopLogProbabilities {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.TopProbabilities) != 0 {
		const prefix string = ",\"top_probs\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.TopProbabilities {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenProbability) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenProbability) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenProbability) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenProbability) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions1(in *jlexer.Lexer, out *Timings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "prompt_n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptN = int(in.Int())
			}
		case "prompt_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptMS = float64(in.Float64())
			}
		case "prompt_per_second":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptPerSecond = float64(in.Float64())
			}
		case "predicted_n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PredictedN = int(in.Int())
			}
		case "predicted_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PredictedMS = float64(in.Float64())
			}
		case "predicted_per_second":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PredictedPerSecond = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions1(out *jwriter.Writer, in Timings) {
	out.RawByte('{')
	first := true
	_ = first
	if in.PromptN != 0 {
		const prefix string = ",\"prompt_n\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.PromptN))
	}
	if in.PromptMS != 0 {
		const prefix string = ",\"prompt_ms\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.PromptMS))
	}
	if in.PromptPerSecond != 0 {
		const prefix string = ",\"prompt_per_second\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.PromptPerSecond))
	}
	if in.PredictedN != 0 {
		const prefix string = ",\"predicted_n\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.PredictedN))
	}
	if in.PredictedMS != 0 {
		const prefix string = ",\"predicted_ms\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.PredictedMS))
	}
	if in.PredictedPerSecond != 0 {
		const prefix string = ",\"predicted_per_second\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.PredictedPerSecond))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Timings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Timings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Timings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Timings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions1(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions2(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "tokens":
			if in.IsNull() {
				in.Skip()
				out.Tokens = nil
			} else {
				in.Delim('[')
				if out.Tokens == nil {
					if !in.IsDelim(']') {
						out.Tokens = make([]int, 0, 8)
					} else {
						out.Tokens = []int{}
					}
				} else {
					out.Tokens = (out.Tokens)[:0]
				}
				for !in.IsDelim(']') {
					var v10 int
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = int(in.Int())
					}
					out.Tokens = append(out.Tokens, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stop":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stop = bool(in.Bool())
			}
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "prompt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Prompt).UnmarshalJSON(data))
				}
			}
		case "stop_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopType = string(in.String())
			}
		case "stopping_word":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StoppingWord = string(in.String())
			}
		case "generation_settings":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.GenerationSettings).UnmarshalEasyJSON(in)
			}
		case "timings":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Timings).UnmarshalEasyJSON(in)
			}
		case "completion_probabilities":
			if in.IsNull() {
				in.Skip()
				out.CompletionProbabilities = nil
			} else {
				in.Delim('[')
				if out.CompletionProbabilities == nil {
					if !in.IsDelim(']') {
						out.CompletionProbabilities = make([]TokenProbability, 0, 0)
					} else {
						out.CompletionProbabilities = []TokenProbability{}
					}
				} else {
					out.CompletionProbabilities = (out.CompletionProbabilities)[:0]
				}
				for !in.IsDelim(']') {
					var v11 TokenProbability
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					out.CompletionProbabilities = append(out.CompletionProbabilities, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "probs":
			if in.IsNull() {
				in.Skip()
				out.Probabilities = nil
			} else {
				in.Delim('[')
				if out.Probabilities == nil {
					if !in.IsDelim(']') {
						out.Probabilities = make([]TokenProbability, 0, 0)
					} else {
						out.Probabilities = []TokenProbability{}
					}
				} else {
					out.Probabilities = (out.Probabilities)[:0]
				}
				for !in.IsDelim(']') {
					var v12 TokenProbability
					if in.IsNull() {
						in.Skip()
					} else {
						(v12).UnmarshalEasyJSON(in)
					}
					out.Probabilities = append(out.Probabilities, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tokens_cached":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokensCached = int(in.Int())
			}
		case "tokens_evaluated":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokensEvaluated = int(in.Int())
			}
		case "truncated":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Truncated = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions2(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Content != "" {
		const prefix string = ",\"content\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	if len(in.Tokens) != 0 {
		const prefix string = ",\"tokens\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v13, v14 := range in.Tokens {
				if v13 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v14))
			}
			out.RawByte(']')
		}
	}
	if in.Stop {
		const prefix string = ",\"stop\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Stop))
	}
	if in.Model != "" {
		const prefix string = ",\"model\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Model))
	}
	if len(in.Prompt) != 0 {
		const prefix string = ",\"prompt\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Prompt).MarshalJSON())
	}
	if in.StopType != "" {
		const prefix string = ",\"stop_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StopType))
	}
	if in.StoppingWord != "" {
		const prefix string = ",\"stopping_word\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StoppingWord))
	}
	if true {
		const prefix string = ",\"generation_settings\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.GenerationSettings).MarshalEasyJSON(out)
	}
	if true {
		const prefix string = ",\"timings\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Timings).MarshalEasyJSON(out)
	}
	if len(in.CompletionProbabilities) != 0 {
		const prefix string = ",\"completion_probabilities\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.CompletionProbabilities {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Probabilities) != 0 {
		const prefix string = ",\"probs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v17, v18 := range in.Probabilities {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.TokensCached != 0 {
		const prefix string = ",\"tokens_cached\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TokensCached))
	}
	if in.TokensEvaluated != 0 {
		const prefix string = ",\"tokens_evaluated\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TokensEvaluated))
	}
	if in.Truncated {
		const prefix string = ",\"truncated\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Truncated))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions2(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions3(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "prompt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Prompt).UnmarshalJSON(data))
				}
			}
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "n_predict":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NPredict = int(in.Int())
			}
		case "n_cmpl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NCmpl = int(in.Int())
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float64(in.Float64())
			}
		case "dynatemp_range":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DynamicTemperatureRange = float64(in.Float64())
			}
		case "dynatemp_exponent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DynamicTemperatureExponent = float64(in.Float64())
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopK = int(in.Int())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float64(in.Float64())
			}
		case "min_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinP = float64(in.Float64())
			}
		case "stop":
			if in.IsNull() {
				in.Skip()
				out.Stop = nil
			} else {
				in.Delim('[')
				if out.Stop == nil {
					if !in.IsDelim(']') {
						out.Stop = make([]string, 0, 4)
					} else {
						out.Stop = []string{}
					}
				} else {
					out.Stop = (out.Stop)[:0]
				}
				for !in.IsDelim(']') {
					var v19 string
					if in.IsNull() {
						in.Skip()
					} else {
						v19 = string(in.String())
					}
					out.Stop = append(out.Stop, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "typical_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TypicalP = float64(in.Float64())
			}
		case "repeat_penalty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RepeatPenalty = float64(in.Float64())
			}
		case "repeat_last_n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RepeatLastN = int(in.Int())
			}
		case "presence_penalty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PresencePenalty = float64(in.Float64())
			}
		case "frequency_penalty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FrequencyPenalty = float64(in.Float64())
			}
		case "dry_multiplier":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DryMultiplier = float64(in.Float64())
			}
		case "dry_base":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DryBase = float64(in.Float64())
			}
		case "dry_allowed_length":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DryAllowedLength = int(in.Int())
			}
		case "dry_penalty_last_n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DryPenaltyLastN = int(in.Int())
			}
		case "dry_sequence_breakers":
			if in.IsNull() {
				in.Skip()
				out.DrySequenceBreakers = nil
			} else {
				in.Delim('[')
				if out.DrySequenceBreakers == nil {
					if !in.IsDelim(']') {
						out.DrySequenceBreakers = make([]string, 0, 4)
					} else {
						out.DrySequenceBreakers = []string{}
					}
				} else {
					out.DrySequenceBreakers = (out.DrySequenceBreakers)[:0]
				}
				for !in.IsDelim(']') {
					var v20 string
					if in.IsNull() {
						in.Skip()
					} else {
						v20 = string(in.String())
					}
					out.DrySequenceBreakers = append(out.DrySequenceBreakers, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "mirostat":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mirostat = int(in.Int())
			}
		case "mirostat_tau":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MirostatTau = float64(in.Float64())
			}
		case "mirostat_eta":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MirostatEta = float64(in.Float64())
			}
		case "grammar":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Grammar = string(in.String())
			}
		case "json_schema":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.JSONSchema).UnmarshalJSON(data))
				}
			}
		case "seed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Seed = int64(in.Int64())
			}
		case "n_probs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NProbs = int(in.Int())
			}
		case "return_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReturnTokens = bool(in.Bool())
			}
		case "response_fields":
			if in.IsNull() {
				in.Skip()
				out.ResponseFields = nil
			} else {
				in.Delim('[')
				if out.ResponseFields == nil {
					if !in.IsDelim(']') {
						out.ResponseFields = make([]string, 0, 4)
					} else {
						out.ResponseFields = []string{}
					}
				} else {
					out.ResponseFields = (out.ResponseFields)[:0]
				}
				for !in.IsDelim(']') {
					var v21 string
					if in.IsNull() {
						in.Skip()
					} else {
						v21 = string(in.String())
					}
					out.ResponseFields = append(out.ResponseFields, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "cache_prompt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CachePrompt = bool(in.Bool())
			}
		case "id_slot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IDSlot = int(in.Int())
			}
		case "lora":
			if in.IsNull() {
				in.Skip()
				out.LoRA = nil
			} else {
				in.Delim('[')
				if out.LoRA == nil {
					if !in.IsDelim(']') {
						out.LoRA = make([]LoRAAdapter, 0, 4)
					} else {
						out.LoRA = []LoRAAdapter{}
					}
				} else {
					out.LoRA = (out.LoRA)[:0]
				}
				for !in.IsDelim(']') {
					var v22 LoRAAdapter
					if in.IsNull() {
						in.Skip()
					} else {
						(v22).UnmarshalEasyJSON(in)
					}
					out.LoRA = append(out.LoRA, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions3(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"prompt\":"
		out.RawString(prefix[1:])
		out.Raw((in.Prompt).MarshalJSON())
	}
	if in.Model != "" {
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.Bool(bool(in.Stream))
	}
	if in.NPredict != 0 {
		const prefix string = ",\"n_predict\":"
		out.RawString(prefix)
		out.Int(int(in.NPredict))
	}
	if in.NCmpl != 0 {
		const prefix string = ",\"n_cmpl\":"
		out.RawString(prefix)
		out.Int(int(in.NCmpl))
	}
	if in.Temperature != 0 {
		const prefix string = ",\"temperature\":"
		out.RawString(prefix)
		out.Float64(float64(in.Temperature))
	}
	if in.DynamicTemperatureRange != 0 {
		const prefix string = ",\"dynatemp_range\":"
		out.RawString(prefix)
		out.Float64(float64(in.DynamicTemperatureRange))
	}
	if in.DynamicTemperatureExponent != 0 {
		const prefix string = ",\"dynatemp_exponent\":"
		out.RawString(prefix)
		out.Float64(float64(in.DynamicTemperatureExponent))
	}
	if in.TopK != 0 {
		const prefix string = ",\"top_k\":"
		out.RawString(prefix)
		out.Int(int(in.TopK))
	}
	if in.TopP != 0 {
		const prefix string = ",\"top_p\":"
		out.RawString(prefix)
		out.Float64(float64(in.TopP))
	}
	if in.MinP != 0 {
		const prefix string = ",\"min_p\":"
		out.RawString(prefix)
		out.Float64(float64(in.MinP))
	}
	if len(in.Stop) != 0 {
		const prefix string = ",\"stop\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v23, v24 := range in.Stop {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	if in.TypicalP != 0 {
		const prefix string = ",\"typical_p\":"
		out.RawString(prefix)
		out.Float64(float64(in.TypicalP))
	}
	if in.RepeatPenalty != 0 {
		const prefix string = ",\"repeat_penalty\":"
		out.RawString(prefix)
		out.Float64(float64(in.RepeatPenalty))
	}
	if in.RepeatLastN != 0 {
		const prefix string = ",\"repeat_last_n\":"
		out.RawString(prefix)
		out.Int(int(in.RepeatLastN))
	}
	if in.PresencePenalty != 0 {
		const prefix string = ",\"presence_penalty\":"
		out.RawString(prefix)
		out.Float64(float64(in.PresencePenalty))
	}
	if in.FrequencyPenalty != 0 {
		const prefix string = ",\"frequency_penalty\":"
		out.RawString(prefix)
		out.Float64(float64(in.FrequencyPenalty))
	}
	if in.DryMultiplier != 0 {
		const prefix string = ",\"dry_multiplier\":"
		out.RawString(prefix)
		out.Float64(float64(in.DryMultiplier))
	}
	if in.DryBase != 0 {
		const prefix string = ",\"dry_base\":"
		out.RawString(prefix)
		out.Float64(float64(in.DryBase))
	}
	if in.DryAllowedLength != 0 {
		const prefix string = ",\"dry_allowed_length\":"
		out.RawString(prefix)
		out.Int(int(in.DryAllowedLength))
	}
	if in.DryPenaltyLastN != 0 {
		const prefix string = ",\"dry_penalty_last_n\":"
		out.RawString(prefix)
		out.Int(int(in.DryPenaltyLastN))
	}
	if len(in.DrySequenceBreakers) != 0 {
		const prefix string = ",\"dry_sequence_breakers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v25, v26 := range in.DrySequenceBreakers {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	if in.Mirostat != 0 {
		const prefix string = ",\"mirostat\":"
		out.RawString(prefix)
		out.Int(int(in.Mirostat))
	}
	if in.MirostatTau != 0 {
		const prefix string = ",\"mirostat_tau\":"
		out.RawString(prefix)
		out.Float64(float64(in.MirostatTau))
	}
	if in.MirostatEta != 0 {
		const prefix string = ",\"mirostat_eta\":"
		out.RawString(prefix)
		out.Float64(float64(in.MirostatEta))
	}
	if in.Grammar != "" {
		const prefix string = ",\"grammar\":"
		out.RawString(prefix)
		out.String(string(in.Grammar))
	}
	if len(in.JSONSchema) != 0 {
		const prefix string = ",\"json_schema\":"
		out.RawString(prefix)
		out.Raw((in.JSONSchema).MarshalJSON())
	}
	if in.Seed != 0 {
		const prefix string = ",\"seed\":"
		out.RawString(prefix)
		out.Int64(int64(in.Seed))
	}
	if in.NProbs != 0 {
		const prefix string = ",\"n_probs\":"
		out.RawString(prefix)
		out.Int(int(in.NProbs))
	}
	if in.ReturnTokens {
		const prefix string = ",\"return_tokens\":"
		out.RawString(prefix)
		out.Bool(bool(in.ReturnTokens))
	}
	if len(in.ResponseFields) != 0 {
		const prefix string = ",\"response_fields\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v27, v28 := range in.ResponseFields {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	if in.CachePrompt {
		const prefix string = ",\"cache_prompt\":"
		out.RawString(prefix)
		out.Bool(bool(in.CachePrompt))
	}
	if in.IDSlot != 0 {
		const prefix string = ",\"id_slot\":"
		out.RawString(prefix)
		out.Int(int(in.IDSlot))
	}
	if len(in.LoRA) != 0 {
		const prefix string = ",\"lora\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v29, v30 := range in.LoRA {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions3(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions4(in *jlexer.Lexer, out *LoRAAdapter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "scale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scale = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions4(out *jwriter.Writer, in LoRAAdapter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"scale\":"
		out.RawString(prefix)
		out.Float64(float64(in.Scale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoRAAdapter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoRAAdapter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoRAAdapter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoRAAdapter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions4(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions5(in *jlexer.Lexer, out *GenerationSettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "n_predict":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NPredict = int(in.Int())
			}
		case "n_ctx":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NCtx = int(in.Int())
			}
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float64(in.Float64())
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopK = int(in.Int())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float64(in.Float64())
			}
		case "min_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinP = float64(in.Float64())
			}
		case "stop":
			if in.IsNull() {
				in.Skip()
				out.Stop = nil
			} else {
				in.Delim('[')
				if out.Stop == nil {
					if !in.IsDelim(']') {
						out.Stop = make([]string, 0, 4)
					} else {
						out.Stop = []string{}
					}
				} else {
					out.Stop = (out.Stop)[:0]
				}
				for !in.IsDelim(']') {
					var v31 string
					if in.IsNull() {
						in.Skip()
					} else {
						v31 = string(in.String())
					}
					out.Stop = append(out.Stop, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "samplers":
			if in.IsNull() {
				in.Skip()
				out.Samplers = nil
			} else {
				in.Delim('[')
				if out.Samplers == nil {
					if !in.IsDelim(']') {
						out.Samplers = make([]string, 0, 4)
					} else {
						out.Samplers = []string{}
					}
				} else {
					out.Samplers = (out.Samplers)[:0]
				}
				for !in.IsDelim(']') {
					var v32 string
					if in.IsNull() {
						in.Skip()
					} else {
						v32 = string(in.String())
					}
					out.Samplers = append(out.Samplers, v32)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions5(out *jwriter.Writer, in GenerationSettings) {
	out.RawByte('{')
	first := true
	_ = first
	if in.NPredict != 0 {
		const prefix string = ",\"n_predict\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.NPredict))
	}
	if in.NCtx != 0 {
		const prefix string = ",\"n_ctx\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NCtx))
	}
	if in.Model != "" {
		const prefix string = ",\"model\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Model))
	}
	if in.Temperature != 0 {
		const prefix string = ",\"temperature\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Temperature))
	}
	if in.TopK != 0 {
		const prefix string = ",\"top_k\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TopK))
	}
	if in.TopP != 0 {
		const prefix string = ",\"top_p\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.TopP))
	}
	if in.MinP != 0 {
		const prefix string = ",\"min_p\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.MinP))
	}
	if len(in.Stop) != 0 {
		const prefix string = ",\"stop\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v33, v34 := range in.Stop {
				if v33 > 0 {
					out.RawByte(',')
				}
				out.String(string(v34))
			}
			out.RawByte(']')
		}
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Stream))
	}
	if len(in.Samplers) != 0 {
		const prefix string = ",\"samplers\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v35, v36 := range in.Samplers {
				if v35 > 0 {
					out.RawByte(',')
				}
				out.String(string(v36))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenerationSettings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenerationSettings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaCompletions5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenerationSettings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenerationSettings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaCompletions5(l, v)
}
