// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package embeddings

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "embeddings":
			if in.IsNull() {
				in.Skip()
				out.Embeddings = nil
			} else {
				in.Delim('[')
				if out.Embeddings == nil {
					if !in.IsDelim(']') {
						out.Embeddings = make([][]float64, 0, 2)
					} else {
						out.Embeddings = [][]float64{}
					}
				} else {
					out.Embeddings = (out.Embeddings)[:0]
				}
				for !in.IsDelim(']') {
					var v1 []float64
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]float64, 0, 8)
							} else {
								v1 = []float64{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 float64
							if in.IsNull() {
								in.Skip()
							} else {
								v2 = float64(in.Float64())
							}
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Embeddings = append(out.Embeddings, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total_duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalDuration = int64(in.Int64())
			}
		case "load_duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LoadDuration = int64(in.Int64())
			}
		case "prompt_eval_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptEvalCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"embeddings\":"
		out.RawString(prefix)
		if in.Embeddings == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Embeddings {
				if v3 > 0 {
					out.RawByte(',')
				}
				if v4 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v5, v6 := range v4 {
						if v5 > 0 {
							out.RawByte(',')
						}
						out.Float64(float64(v6))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	if in.TotalDuration != 0 {
		const prefix string = ",\"total_duration\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalDuration))
	}
	if in.LoadDuration != 0 {
		const prefix string = ",\"load_duration\":"
		out.RawString(prefix)
		out.Int64(int64(in.LoadDuration))
	}
	if in.PromptEvalCount != 0 {
		const prefix string = ",\"prompt_eval_count\":"
		out.RawString(prefix)
		out.Int(int(in.PromptEvalCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings1(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Input).UnmarshalJSON(data))
				}
			}
		case "truncate":
			if in.IsNull() {
				in.Skip()
				out.Truncate = nil
			} else {
				if out.Truncate == nil {
					out.Truncate = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Truncate = bool(in.Bool())
				}
			}
		case "dimensions":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dimensions = int(in.Int())
			}
		case "keep_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KeepAlive = string(in.String())
			}
		case "options":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Options).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings1(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		out.Raw((in.Input).MarshalJSON())
	}
	if in.Truncate != nil {
		const prefix string = ",\"truncate\":"
		out.RawString(prefix)
		out.Bool(bool(*in.Truncate))
	}
	if in.Dimensions != 0 {
		const prefix string = ",\"dimensions\":"
		out.RawString(prefix)
		out.Int(int(in.Dimensions))
	}
	if in.KeepAlive != "" {
		const prefix string = ",\"keep_alive\":"
		out.RawString(prefix)
		out.String(string(in.KeepAlive))
	}
	if len(in.Options) != 0 {
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		out.Raw((in.Options).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientOllamaEmbeddings1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientOllamaEmbeddings1(l, v)
}
