// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package server

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer(in *jlexer.Lexer, out *Props) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ModelPath = string(in.String())
			}
		case "chat_template":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatTemplate = string(in.String())
			}
		case "total_slots":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalSlots = int(in.Int())
			}
		case "modalities":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Modalities).UnmarshalEasyJSON(in)
			}
		case "is_sleeping":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsSleeping = bool(in.Bool())
			}
		case "default_generation_settings":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DefaultGenerationSettings).UnmarshalEasyJSON(in)
			}
		case "chat_template_caps":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ChatTemplateCapabilities).UnmarshalJSON(data))
				}
			}
		case "media_marker":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaMarker = string(in.String())
			}
		case "build_info":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BuildInfo = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer(out *jwriter.Writer, in Props) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ModelPath != "" {
		const prefix string = ",\"model_path\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ModelPath))
	}
	if in.ChatTemplate != "" {
		const prefix string = ",\"chat_template\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ChatTemplate))
	}
	if in.TotalSlots != 0 {
		const prefix string = ",\"total_slots\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TotalSlots))
	}
	if true {
		const prefix string = ",\"modalities\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Modalities).MarshalEasyJSON(out)
	}
	if in.IsSleeping {
		const prefix string = ",\"is_sleeping\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.IsSleeping))
	}
	if true {
		const prefix string = ",\"default_generation_settings\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.DefaultGenerationSettings).MarshalEasyJSON(out)
	}
	if len(in.ChatTemplateCapabilities) != 0 {
		const prefix string = ",\"chat_template_caps\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.ChatTemplateCapabilities).MarshalJSON())
	}
	if in.MediaMarker != "" {
		const prefix string = ",\"media_marker\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MediaMarker))
	}
	if in.BuildInfo != "" {
		const prefix string = ",\"build_info\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.BuildInfo))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Props) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Props) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Props) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Props) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer1(in *jlexer.Lexer, out *Modalities) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "vision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Vision = bool(in.Bool())
			}
		case "audio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Audio = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer1(out *jwriter.Writer, in Modalities) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Vision {
		const prefix string = ",\"vision\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Vision))
	}
	if in.Audio {
		const prefix string = ",\"audio\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Audio))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Modalities) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Modalities) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Modalities) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Modalities) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer1(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer2(in *jlexer.Lexer, out *HealthResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer2(out *jwriter.Writer, in HealthResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer2(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer3(in *jlexer.Lexer, out *GenerationSettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "n_predict":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NPredict = int(in.Int())
			}
		case "n_ctx":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NCtx = int(in.Int())
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float64(in.Float64())
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopK = int(in.Int())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float64(in.Float64())
			}
		case "min_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinP = float64(in.Float64())
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "stop":
			if in.IsNull() {
				in.Skip()
				out.Stop = nil
			} else {
				in.Delim('[')
				if out.Stop == nil {
					if !in.IsDelim(']') {
						out.Stop = make([]string, 0, 4)
					} else {
						out.Stop = []string{}
					}
				} else {
					out.Stop = (out.Stop)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Stop = append(out.Stop, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "samplers":
			if in.IsNull() {
				in.Skip()
				out.Samplers = nil
			} else {
				in.Delim('[')
				if out.Samplers == nil {
					if !in.IsDelim(']') {
						out.Samplers = make([]string, 0, 4)
					} else {
						out.Samplers = []string{}
					}
				} else {
					out.Samplers = (out.Samplers)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.Samplers = append(out.Samplers, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer3(out *jwriter.Writer, in GenerationSettings) {
	out.RawByte('{')
	first := true
	_ = first
	if in.NPredict != 0 {
		const prefix string = ",\"n_predict\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.NPredict))
	}
	if in.NCtx != 0 {
		const prefix string = ",\"n_ctx\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NCtx))
	}
	if in.Temperature != 0 {
		const prefix string = ",\"temperature\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Temperature))
	}
	if in.TopK != 0 {
		const prefix string = ",\"top_k\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TopK))
	}
	if in.TopP != 0 {
		const prefix string = ",\"top_p\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.TopP))
	}
	if in.MinP != 0 {
		const prefix string = ",\"min_p\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.MinP))
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Stream))
	}
	if len(in.Stop) != 0 {
		const prefix string = ",\"stop\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v3, v4 := range in.Stop {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	if len(in.Samplers) != 0 {
		const prefix string = ",\"samplers\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Samplers {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenerationSettings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenerationSettings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientLlamaServer3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenerationSettings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenerationSettings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientLlamaServer3(l, v)
}
