// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package batches

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"

	messages "go.osspkg.com/llm-client/anthropic/messages"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches(in *jlexer.Lexer, out *ResultPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
				out.Message = nil
			} else {
				if out.Message == nil {
					out.Message = new(messages.Response)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Message).UnmarshalEasyJSON(in)
				}
			}
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(ErrorPayload)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Error).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches(out *jwriter.Writer, in ResultPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Message != nil {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		(*in.Message).MarshalEasyJSON(out)
	}
	if in.Error != nil {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		(*in.Error).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResultPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResultPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches1(in *jlexer.Lexer, out *Result) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "custom_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CustomID = string(in.String())
			}
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Result).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches1(out *jwriter.Writer, in Result) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"custom_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CustomID))
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		(in.Result).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Result) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Result) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Result) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Result) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches1(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches2(in *jlexer.Lexer, out *RequestItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "custom_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CustomID = string(in.String())
			}
		case "params":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Params).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches2(out *jwriter.Writer, in RequestItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"custom_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CustomID))
	}
	{
		const prefix string = ",\"params\":"
		out.RawString(prefix)
		(in.Params).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches2(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches3(in *jlexer.Lexer, out *RequestCounts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "processing":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Processing = int(in.Int())
			}
		case "succeeded":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Succeeded = int(in.Int())
			}
		case "errored":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Errored = int(in.Int())
			}
		case "canceled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Canceled = int(in.Int())
			}
		case "expired":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Expired = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches3(out *jwriter.Writer, in RequestCounts) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Processing != 0 {
		const prefix string = ",\"processing\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Processing))
	}
	if in.Succeeded != 0 {
		const prefix string = ",\"succeeded\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Succeeded))
	}
	if in.Errored != 0 {
		const prefix string = ",\"errored\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Errored))
	}
	if in.Canceled != 0 {
		const prefix string = ",\"canceled\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Canceled))
	}
	if in.Expired != 0 {
		const prefix string = ",\"expired\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Expired))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestCounts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestCounts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestCounts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestCounts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches3(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches4(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "requests":
			if in.IsNull() {
				in.Skip()
				out.Requests = nil
			} else {
				in.Delim('[')
				if out.Requests == nil {
					if !in.IsDelim(']') {
						out.Requests = make([]RequestItem, 0, 0)
					} else {
						out.Requests = []RequestItem{}
					}
				} else {
					out.Requests = (out.Requests)[:0]
				}
				for !in.IsDelim(']') {
					var v1 RequestItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Requests = append(out.Requests, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					(out.Metadata)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches4(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"requests\":"
		out.RawString(prefix[1:])
		if in.Requests == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Requests {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Metadata {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches4(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches5(in *jlexer.Lexer, out *ListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Batch, 0, 0)
					} else {
						out.Data = []Batch{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v6 Batch
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "has_more":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasMore = bool(in.Bool())
			}
		case "first_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstID = string(in.String())
			}
		case "last_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches5(out *jwriter.Writer, in ListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Data {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"has_more\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasMore))
	}
	if in.FirstID != "" {
		const prefix string = ",\"first_id\":"
		out.RawString(prefix)
		out.String(string(in.FirstID))
	}
	if in.LastID != "" {
		const prefix string = ",\"last_id\":"
		out.RawString(prefix)
		out.String(string(in.LastID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches5(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches6(in *jlexer.Lexer, out *ErrorPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches6(out *jwriter.Writer, in ErrorPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches6(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches7(in *jlexer.Lexer, out *Batch) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "processing_status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProcessingStatus = string(in.String())
			}
		case "request_counts":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.RequestCounts).UnmarshalEasyJSON(in)
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "ended_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndedAt = string(in.String())
			}
		case "expires_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresAt = string(in.String())
			}
		case "results_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ResultsURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches7(out *jwriter.Writer, in Batch) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"processing_status\":"
		out.RawString(prefix)
		out.String(string(in.ProcessingStatus))
	}
	if true {
		const prefix string = ",\"request_counts\":"
		out.RawString(prefix)
		(in.RequestCounts).MarshalEasyJSON(out)
	}
	if in.CreatedAt != "" {
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.EndedAt != "" {
		const prefix string = ",\"ended_at\":"
		out.RawString(prefix)
		out.String(string(in.EndedAt))
	}
	if in.ExpiresAt != "" {
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.String(string(in.ExpiresAt))
	}
	if in.ResultsURL != "" {
		const prefix string = ",\"results_url\":"
		out.RawString(prefix)
		out.String(string(in.ResultsURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Batch) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Batch) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicBatches7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Batch) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Batch) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicBatches7(l, v)
}
