// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels(in *jlexer.Lexer, out *Model) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "display_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DisplayName = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "max_input_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxInputTokens = int(in.Int())
			}
		case "max_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTokens = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels(out *jwriter.Writer, in Model) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"display_name\":"
		out.RawString(prefix)
		out.String(string(in.DisplayName))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.MaxInputTokens != 0 {
		const prefix string = ",\"max_input_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.MaxInputTokens))
	}
	if in.MaxTokens != 0 {
		const prefix string = ",\"max_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.MaxTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Model) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Model) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Model) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Model) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels1(in *jlexer.Lexer, out *ListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Model, 0, 0)
					} else {
						out.Data = []Model{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Model
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "first_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstID = string(in.String())
			}
		case "last_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = string(in.String())
			}
		case "has_more":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasMore = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels1(out *jwriter.Writer, in ListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.FirstID != "" {
		const prefix string = ",\"first_id\":"
		out.RawString(prefix)
		out.String(string(in.FirstID))
	}
	if in.LastID != "" {
		const prefix string = ",\"last_id\":"
		out.RawString(prefix)
		out.String(string(in.LastID))
	}
	{
		const prefix string = ",\"has_more\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasMore))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicModels1(l, v)
}
