// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package messages

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages(in *jlexer.Lexer, out *Usage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "input_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InputTokens = int(in.Int())
			}
		case "output_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputTokens = int(in.Int())
			}
		case "cache_creation_input_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CacheCreationInputTokens = int(in.Int())
			}
		case "cache_read_input_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CacheReadInputTokens = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages(out *jwriter.Writer, in Usage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"input_tokens\":"
		out.RawString(prefix[1:])
		out.Int(int(in.InputTokens))
	}
	{
		const prefix string = ",\"output_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.OutputTokens))
	}
	if in.CacheCreationInputTokens != 0 {
		const prefix string = ",\"cache_creation_input_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.CacheCreationInputTokens))
	}
	if in.CacheReadInputTokens != 0 {
		const prefix string = ",\"cache_read_input_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.CacheReadInputTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Usage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Usage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Usage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Usage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages1(in *jlexer.Lexer, out *ToolUseBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Input).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages1(out *jwriter.Writer, in ToolUseBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		out.Raw((in.Input).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolUseBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolUseBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolUseBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolUseBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages1(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages2(in *jlexer.Lexer, out *ToolResultBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "tool_use_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ToolUseID = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Content).UnmarshalEasyJSON(in)
			}
		case "is_error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsError = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages2(out *jwriter.Writer, in ToolResultBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"tool_use_id\":"
		out.RawString(prefix)
		out.String(string(in.ToolUseID))
	}
	if len(in.Content) != 0 {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		(in.Content).MarshalEasyJSON(out)
	}
	if in.IsError {
		const prefix string = ",\"is_error\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsError))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolResultBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolResultBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolResultBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolResultBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages2(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages3(in *jlexer.Lexer, out *ToolChoice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "disable_parallel_tool_use":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DisableParallelToolUse = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages3(out *jwriter.Writer, in ToolChoice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.DisableParallelToolUse {
		const prefix string = ",\"disable_parallel_tool_use\":"
		out.RawString(prefix)
		out.Bool(bool(in.DisableParallelToolUse))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolChoice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolChoice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolChoice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolChoice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages3(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages4(in *jlexer.Lexer, out *Tool) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "input_schema":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.InputSchema).UnmarshalJSON(data))
				}
			}
		case "cache_control":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CacheControl).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages4(out *jwriter.Writer, in Tool) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"input_schema\":"
		out.RawString(prefix)
		out.Raw((in.InputSchema).MarshalJSON())
	}
	if len(in.CacheControl) != 0 {
		const prefix string = ",\"cache_control\":"
		out.RawString(prefix)
		out.Raw((in.CacheControl).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Tool) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Tool) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Tool) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Tool) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages4(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages5(in *jlexer.Lexer, out *ThinkingConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "budget_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTokens = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages5(out *jwriter.Writer, in ThinkingConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"budget_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.BudgetTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThinkingConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThinkingConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThinkingConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThinkingConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages5(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages6(in *jlexer.Lexer, out *ThinkingBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Thinking = string(in.String())
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages6(out *jwriter.Writer, in ThinkingBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		out.String(string(in.Thinking))
	}
	{
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThinkingBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThinkingBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThinkingBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThinkingBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages6(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages7(in *jlexer.Lexer, out *TextBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "citations":
			if in.IsNull() {
				in.Skip()
				out.Citations = nil
			} else {
				in.Delim('[')
				if out.Citations == nil {
					if !in.IsDelim(']') {
						out.Citations = make([]Citation, 0, 0)
					} else {
						out.Citations = []Citation{}
					}
				} else {
					out.Citations = (out.Citations)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Citation
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Citations = append(out.Citations, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages7(out *jwriter.Writer, in TextBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	if len(in.Citations) != 0 {
		const prefix string = ",\"citations\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.Citations {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TextBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TextBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TextBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TextBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages7(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages8(in *jlexer.Lexer, out *StreamEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Message).UnmarshalJSON(data))
				}
			}
		case "content_block":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ContentBlock).UnmarshalJSON(data))
				}
			}
		case "delta":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Delta).UnmarshalJSON(data))
				}
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				out.Usage = nil
			} else {
				if out.Usage == nil {
					out.Usage = new(Usage)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Usage).UnmarshalEasyJSON(in)
				}
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Error).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages8(out *jwriter.Writer, in StreamEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Index != 0 {
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Int(int(in.Index))
	}
	if len(in.Message) != 0 {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.Raw((in.Message).MarshalJSON())
	}
	if len(in.ContentBlock) != 0 {
		const prefix string = ",\"content_block\":"
		out.RawString(prefix)
		out.Raw((in.ContentBlock).MarshalJSON())
	}
	if len(in.Delta) != 0 {
		const prefix string = ",\"delta\":"
		out.RawString(prefix)
		out.Raw((in.Delta).MarshalJSON())
	}
	if in.Usage != nil {
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		(*in.Usage).MarshalEasyJSON(out)
	}
	if len(in.Error) != 0 {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.Raw((in.Error).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StreamEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StreamEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StreamEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StreamEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages8(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages9(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Content).UnmarshalEasyJSON(in)
			}
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "stop_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopReason = string(in.String())
			}
		case "stop_sequence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopSequence = string(in.String())
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Usage).UnmarshalEasyJSON(in)
			}
		case "container":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Container).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages9(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		(in.Content).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	if in.StopReason != "" {
		const prefix string = ",\"stop_reason\":"
		out.RawString(prefix)
		out.String(string(in.StopReason))
	}
	if in.StopSequence != "" {
		const prefix string = ",\"stop_sequence\":"
		out.RawString(prefix)
		out.String(string(in.StopSequence))
	}
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		(in.Usage).MarshalEasyJSON(out)
	}
	if len(in.Container) != 0 {
		const prefix string = ",\"container\":"
		out.RawString(prefix)
		out.Raw((in.Container).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages9(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages10(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]Message, 0, 1)
					} else {
						out.Messages = []Message{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Message
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "max_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTokens = int(in.Int())
			}
		case "system":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.System).UnmarshalEasyJSON(in)
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float64(in.Float64())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float64(in.Float64())
			}
		case "top_k":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopK = int(in.Int())
			}
		case "stop_sequences":
			if in.IsNull() {
				in.Skip()
				out.StopSequences = nil
			} else {
				in.Delim('[')
				if out.StopSequences == nil {
					if !in.IsDelim(']') {
						out.StopSequences = make([]string, 0, 4)
					} else {
						out.StopSequences = []string{}
					}
				} else {
					out.StopSequences = (out.StopSequences)[:0]
				}
				for !in.IsDelim(']') {
					var v5 string
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = string(in.String())
					}
					out.StopSequences = append(out.StopSequences, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				out.Tools = nil
			} else {
				in.Delim('[')
				if out.Tools == nil {
					if !in.IsDelim(']') {
						out.Tools = make([]Tool, 0, 0)
					} else {
						out.Tools = []Tool{}
					}
				} else {
					out.Tools = (out.Tools)[:0]
				}
				for !in.IsDelim(']') {
					var v6 Tool
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.Tools = append(out.Tools, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tool_choice":
			if in.IsNull() {
				in.Skip()
				out.ToolChoice = nil
			} else {
				if out.ToolChoice == nil {
					out.ToolChoice = new(ToolChoice)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.ToolChoice).UnmarshalEasyJSON(in)
				}
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				out.Thinking = nil
			} else {
				if out.Thinking == nil {
					out.Thinking = new(ThinkingConfig)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Thinking).UnmarshalEasyJSON(in)
				}
			}
		case "output_config":
			if in.IsNull() {
				in.Skip()
				out.OutputConfig = nil
			} else {
				if out.OutputConfig == nil {
					out.OutputConfig = new(OutputConfig)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.OutputConfig).UnmarshalEasyJSON(in)
				}
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					(out.Metadata)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages10(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Messages {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"max_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.MaxTokens))
	}
	if len(in.System) != 0 {
		const prefix string = ",\"system\":"
		out.RawString(prefix)
		(in.System).MarshalEasyJSON(out)
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.Bool(bool(in.Stream))
	}
	if in.Temperature != 0 {
		const prefix string = ",\"temperature\":"
		out.RawString(prefix)
		out.Float64(float64(in.Temperature))
	}
	if in.TopP != 0 {
		const prefix string = ",\"top_p\":"
		out.RawString(prefix)
		out.Float64(float64(in.TopP))
	}
	if in.TopK != 0 {
		const prefix string = ",\"top_k\":"
		out.RawString(prefix)
		out.Int(int(in.TopK))
	}
	if len(in.StopSequences) != 0 {
		const prefix string = ",\"stop_sequences\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v10, v11 := range in.StopSequences {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	if len(in.Tools) != 0 {
		const prefix string = ",\"tools\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v12, v13 := range in.Tools {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.ToolChoice != nil {
		const prefix string = ",\"tool_choice\":"
		out.RawString(prefix)
		(*in.ToolChoice).MarshalEasyJSON(out)
	}
	if in.Thinking != nil {
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		(*in.Thinking).MarshalEasyJSON(out)
	}
	if in.OutputConfig != nil {
		const prefix string = ",\"output_config\":"
		out.RawString(prefix)
		(*in.OutputConfig).MarshalEasyJSON(out)
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.Metadata {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				out.String(string(v14Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages10(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages11(in *jlexer.Lexer, out *RedactedThinkingBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages11(out *jwriter.Writer, in RedactedThinkingBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RedactedThinkingBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RedactedThinkingBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RedactedThinkingBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RedactedThinkingBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages11(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages12(in *jlexer.Lexer, out *OutputConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "format":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Format).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages12(out *jwriter.Writer, in OutputConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Format) != 0 {
		const prefix string = ",\"format\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.Format).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OutputConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OutputConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OutputConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OutputConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages12(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages13(in *jlexer.Lexer, out *MessageDelta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "stop_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopReason = string(in.String())
			}
		case "stop_sequence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopSequence = string(in.String())
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				out.Usage = nil
			} else {
				if out.Usage == nil {
					out.Usage = new(Usage)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Usage).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages13(out *jwriter.Writer, in MessageDelta) {
	out.RawByte('{')
	first := true
	_ = first
	if in.StopReason != "" {
		const prefix string = ",\"stop_reason\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.StopReason))
	}
	if in.StopSequence != "" {
		const prefix string = ",\"stop_sequence\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StopSequence))
	}
	if in.Usage != nil {
		const prefix string = ",\"usage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Usage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageDelta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageDelta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageDelta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageDelta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages13(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages14(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Content).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages14(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		(in.Content).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages14(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages15(in *jlexer.Lexer, out *ImageSource) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "media_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages15(out *jwriter.Writer, in ImageSource) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.MediaType != "" {
		const prefix string = ",\"media_type\":"
		out.RawString(prefix)
		out.String(string(in.MediaType))
	}
	if in.Data != "" {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	if in.URL != "" {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ImageSource) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ImageSource) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ImageSource) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ImageSource) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages15(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages16(in *jlexer.Lexer, out *ImageBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Source).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages16(out *jwriter.Writer, in ImageBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		(in.Source).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ImageBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ImageBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ImageBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ImageBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages16(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages17(in *jlexer.Lexer, out *ErrorPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages17(out *jwriter.Writer, in ErrorPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages17(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages18(in *jlexer.Lexer, out *DocumentSource) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "media_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages18(out *jwriter.Writer, in DocumentSource) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.MediaType != "" {
		const prefix string = ",\"media_type\":"
		out.RawString(prefix)
		out.String(string(in.MediaType))
	}
	if in.Data != "" {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	if in.Text != "" {
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	if in.URL != "" {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DocumentSource) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DocumentSource) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DocumentSource) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DocumentSource) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages18(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages19(in *jlexer.Lexer, out *DocumentBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Source).UnmarshalEasyJSON(in)
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "context":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Context = string(in.String())
			}
		case "citations":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Citations).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages19(out *jwriter.Writer, in DocumentBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		(in.Source).MarshalEasyJSON(out)
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Context != "" {
		const prefix string = ",\"context\":"
		out.RawString(prefix)
		out.String(string(in.Context))
	}
	if len(in.Citations) != 0 {
		const prefix string = ",\"citations\":"
		out.RawString(prefix)
		out.Raw((in.Citations).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DocumentBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DocumentBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DocumentBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DocumentBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages19(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages20(in *jlexer.Lexer, out *CountTokensResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "input_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InputTokens = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages20(out *jwriter.Writer, in CountTokensResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"input_tokens\":"
		out.RawString(prefix[1:])
		out.Int(int(in.InputTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CountTokensResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CountTokensResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CountTokensResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CountTokensResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages20(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages21(in *jlexer.Lexer, out *CountTokensRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]Message, 0, 1)
					} else {
						out.Messages = []Message{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v15 Message
					if in.IsNull() {
						in.Skip()
					} else {
						(v15).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "system":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.System).UnmarshalEasyJSON(in)
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				out.Tools = nil
			} else {
				in.Delim('[')
				if out.Tools == nil {
					if !in.IsDelim(']') {
						out.Tools = make([]Tool, 0, 0)
					} else {
						out.Tools = []Tool{}
					}
				} else {
					out.Tools = (out.Tools)[:0]
				}
				for !in.IsDelim(']') {
					var v16 Tool
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Tools = append(out.Tools, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
				out.Thinking = nil
			} else {
				if out.Thinking == nil {
					out.Thinking = new(ThinkingConfig)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Thinking).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages21(out *jwriter.Writer, in CountTokensRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Messages {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.System) != 0 {
		const prefix string = ",\"system\":"
		out.RawString(prefix)
		(in.System).MarshalEasyJSON(out)
	}
	if len(in.Tools) != 0 {
		const prefix string = ",\"tools\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v19, v20 := range in.Tools {
				if v19 > 0 {
					out.RawByte(',')
				}
				(v20).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Thinking != nil {
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		(*in.Thinking).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CountTokensRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CountTokensRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CountTokensRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CountTokensRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages21(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages22(in *jlexer.Lexer, out *ContentBlockDelta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "partial_json":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PartialJSON = string(in.String())
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Thinking = string(in.String())
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages22(out *jwriter.Writer, in ContentBlockDelta) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Text != "" {
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	if in.PartialJSON != "" {
		const prefix string = ",\"partial_json\":"
		out.RawString(prefix)
		out.String(string(in.PartialJSON))
	}
	if in.Thinking != "" {
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		out.String(string(in.Thinking))
	}
	if in.Signature != "" {
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContentBlockDelta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages22(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContentBlockDelta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages22(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContentBlockDelta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages22(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContentBlockDelta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages22(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages23(in *jlexer.Lexer, out *ContentBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Source).UnmarshalJSON(data))
				}
			}
		case "thinking":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Thinking = string(in.String())
			}
		case "signature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "input":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Input).UnmarshalJSON(data))
				}
			}
		case "tool_use_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ToolUseID = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Content).UnmarshalJSON(data))
				}
			}
		case "is_error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsError = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages23(out *jwriter.Writer, in ContentBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Text != "" {
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	if len(in.Source) != 0 {
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.Raw((in.Source).MarshalJSON())
	}
	if in.Thinking != "" {
		const prefix string = ",\"thinking\":"
		out.RawString(prefix)
		out.String(string(in.Thinking))
	}
	if in.Signature != "" {
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	if in.Data != "" {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	if in.ID != "" {
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if len(in.Input) != 0 {
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		out.Raw((in.Input).MarshalJSON())
	}
	if in.ToolUseID != "" {
		const prefix string = ",\"tool_use_id\":"
		out.RawString(prefix)
		out.String(string(in.ToolUseID))
	}
	if len(in.Content) != 0 {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.Raw((in.Content).MarshalJSON())
	}
	if in.IsError {
		const prefix string = ",\"is_error\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsError))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContentBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages23(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContentBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages23(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContentBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages23(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContentBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages23(l, v)
}
func easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages24(in *jlexer.Lexer, out *Citation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "cited_text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CitedText = string(in.String())
			}
		case "document_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DocumentIndex = int(in.Int())
			}
		case "document_title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DocumentTitle = string(in.String())
			}
		case "start_char_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartCharIndex = int(in.Int())
			}
		case "end_char_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndCharIndex = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages24(out *jwriter.Writer, in Citation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.CitedText != "" {
		const prefix string = ",\"cited_text\":"
		out.RawString(prefix)
		out.String(string(in.CitedText))
	}
	if in.DocumentIndex != 0 {
		const prefix string = ",\"document_index\":"
		out.RawString(prefix)
		out.Int(int(in.DocumentIndex))
	}
	if in.DocumentTitle != "" {
		const prefix string = ",\"document_title\":"
		out.RawString(prefix)
		out.String(string(in.DocumentTitle))
	}
	if in.StartCharIndex != 0 {
		const prefix string = ",\"start_char_index\":"
		out.RawString(prefix)
		out.Int(int(in.StartCharIndex))
	}
	if in.EndCharIndex != 0 {
		const prefix string = ",\"end_char_index\":"
		out.RawString(prefix)
		out.Int(int(in.EndCharIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Citation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages24(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Citation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGoOsspkgComLlmClientAnthropicMessages24(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Citation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages24(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Citation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGoOsspkgComLlmClientAnthropicMessages24(l, v)
}
